name: release
on:
  push:
    tags:
      [ "v*" ]
jobs:
  release:
    runs-on: windows-latest
    steps:
      [
        {
          name: Checkout code,
          uses: actions/checkout@v4
        },
        {
          name: Set up Python,
          uses: actions/setup-python@v5,
          with: { python_version: "3.12" }
        },
        {
          name: Install dependencies,
          run: pip install pyinstaller pytest
        },
        {
          name: Build PyInstaller binary,
          run: pyinstaller --onedir --name wincc_reviewer wincc_reviewer/app/main.py
        },
        {
          name: Create GitHub Release,
          uses: softprops/action-gh-release@v1,
          with: { files: "dist/wincc_reviewer/*" }
        }
      ]
